# Generated by Django 5.0.3 on 2024-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='none', max_length=32, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='none', max_length=64, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='none', max_length=64, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
