# Generated by Django 5.0.3 on 2024-04-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_email_user_password_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('text', models.CharField(max_length=128, verbose_name='Содержание')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.user')),
            ],
        ),
    ]
